app/Http/Controllers/PaymentController.php
app/Http/Controllers/PromotionController.php
app/Http/Controllers/PromotionTierController.php
app/Http/Controllers/RoleController.php
app/Http/Controllers/SubscriptionController.php
app/Http/Controllers/UserController.php
app/Models/Payment.php
app/Models/Promotion.php
app/Models/Promotion_tier.php
app/Models/Role.php
app/Models/Subscription.php
database/factories/PaymentFactory.php
database/factories/PromotionFactory.php
database/factories/PromotionTierFactory.php
database/factories/RoleFactory.php
database/factories/SubscriptionFactory.php
database/migrations/2024_08_19_114434_create_users_table.php
database/migrations/2024_08_19_114521_create_roles_table.php
database/migrations/2024_08_19_114544_create_subscriptions_table.php
database/migrations/2024_08_19_114604_create_payments_table.php
database/migrations/2024_08_19_114630_create_promotions_table.php
database/migrations/2024_08_19_114643_create_promotion_tiers_table.php
database/seeders/PaymentSeeder.php
database/seeders/PromotionSeeder.php
database/seeders/PromotionTierSeeder.php
database/seeders/RoleSeeder.php
database/seeders/SubscriptionSeeder.php
database/seeders/UserSeeder.php

tạo model user và các model khác

migrate user and another

---

app/Http/Controllers/Admin/CategoryController.php
app/Http/Controllers/Admin/CommentController.php
app/Http/Controllers/Admin/StoryController.php
app/Http/Controllers/Admin/UserController.php
resources/views/admin/categories/list-category.blade.php
resources/views/admin/layouts/default.blade.php
resources/views/admin/layouts/header.blade.php
resources/views/admin/stories/list-story.blade.php
resources/views/admin/users/list-user.blade.php
routes/web.php

Sửa 4 trang:
- Danh sách User
- Danh sách Truyện
- Thể loại truyện
- Danh sách comment
Sửa route 4 trang trên

Thêm route cho 4 trang giao diện admin, sửa thôn tin giao diện admin

---

resources/views/home/layout/home/header.blade.php

update lại đường dẫn trên header

update lại đường link

---

resources/views/pay/dieu-khoan.html
resources/views/pay/phuong-thuc-thanh-toan.html

Thêm giao diện điều khoản và phương thức thanh toán

Hoàng-- Thêm giao diện điều khoản và phương thức thanh toán

---

database/migrations/2024_09_29_113650_create_forums_table.php
database/migrations/2024_09_29_113704_create_forums_comment_table.php

có vài lỗicaanf sửa với thêm parent_id cho forum

update lại db forum

---

app/Http/Controllers/ForumCommentController.php
app/Http/Controllers/ForumController.php
app/Models/ForumComment.php
database/migrations/2024_09_29_113704_create_forums_comment_table.php
public/js/app.js
resources/views/home/layout/home/header.blade.php
resources/views/home/thaoluan.blade.php
resources/views/user/chitiet_forum.blade.php
resources/views/user/form_comment_forum.blade.php
resources/views/user/list_comment_forum.blade.php
routes/web.php

form comment của forum và chi tiết forum, bình luận cho từng tus trong forum

commit forum

---

app/Http/Controllers/BookController.php
app/Http/Controllers/ChapterController.php
app/Http/Controllers/ReadingHistoryController.php
app/Http/Controllers/USER/HomeController.php
app/Models/ReadingHistory.php
app/Models/book.php
app/Models/chapter.php
database/migrations/2024_09_19_205805_add_softDeletes_at_to_groups_table.php
database/migrations/2024_10_01_212852_add_price_to_books_table.php
database/migrations/2024_10_03_210100_add_book_id_to_reading_histories_table.php
database/migrations/2024_10_03_214522_add_book_id_to_chapters_table.php
resources/views/admin/stories/chapter/create.blade.php
resources/views/admin/stories/chapter/edit.blade.php
resources/views/admin/stories/episodes/create.blade.php
resources/views/admin/stories/showStory.blade.php
resources/views/home/index.blade.php
resources/views/stories/create.blade.php
resources/views/story/reading.blade.php
resources/views/story/show.blade.php
routes/admin.php
routes/web.php

Hoàn thành lịch sử đọc truyện cho cả người dùng lẫn khách

Lịch sử đọc truyện

---

public/js/app.js
resources/views/user/chitiet_forum.blade.php
resources/views/user/form_comment_comment_forum.blade.php

xong phần bình luận con cho comment của forum

commit forum comment

---

app/Http/Controllers/USER/HomeController.php
resources/views/home/index.blade.php

Sửa hiển thị truyện trang chủ: 
- Chỉ hiển thị những truyện đã duyệt

Sửa hiển thị truyện trang chủ

---

app/Http/Controllers/RatingController.php
app/Models/Like.php
app/Models/Rating.php
database/migrations/2024_10_11_223714_create_likes_rating_table.php
resources/views/rating/rating.blade.php
routes/web.php

update đánh giá

---

app/Http/Controllers/FilterController.php
resources/views/story/index.blade.php
routes/web.php

Hoàn thiện xong phần bộ lọc theo thứ tự, mới cập nhật, lượt thích, lượt xem, số từ

Hoangnv- Bộ lọc trang Danh sách

---

app/Http/Controllers/FilterController.php
resources/views/story/index.blade.php
routes/web.php

Hoàn thiện bộ lọc:
- Sắp xếp theo thứ tự
- Theo chữ cái
- Theo Phân loại
- Theo Tình trạng
các phần bộ lọc liên kết được với nhau

Update bộ lọc

---

app/Http/Controllers/FilterController.php
app/Http/Controllers/USER/HomeController.php
app/Models/chapter.php
resources/views/home/index.blade.php
resources/views/home/the_loai.blade.php
routes/web.php

Sửa phần hiển thị:
- Sáng tác mới nhất 
- Chương mới nhất

Update hiển thị truyện Trang chủ

---

resources/views/home/search.blade.php

giao diện search bị lỗi nên update lại giao diện cho đúng khung

resources search update

---

app/Http/Controllers/Admin/DashboardController.php
app/Http/Controllers/FilterController.php
resources/views/admin/dashboard.blade.php
resources/views/story/index.blade.php
routes/admin.php

Đổ dữ liệu trang Admin Dashboard
Xóa phần thừa trang Danh sách

Đổ dữ liệu trang Admin Dashboard

---

app/Http/Controllers/USER/HomeController.php

Sửa hiển thị chương mới nhất

---

app/Providers/AppServiceProvider.php
resources/views/home/bookmark.blade.php
resources/views/home/convert.blade.php
resources/views/home/gioithieu.blade.php
resources/views/home/gopy.blade.php
resources/views/home/guitinnhan.blade.php
resources/views/home/hd_dangtruyen.blade.php
resources/views/home/hopthu.blade.php
resources/views/home/index.blade.php
resources/views/home/kesach.blade.php
resources/views/home/lichsu.blade.php
resources/views/home/sangtac.blade.php
resources/views/home/search.blade.php
resources/views/home/thaoluan.blade.php
resources/views/home/the_loai.blade.php
resources/views/home/tinnhanmoi.blade.php
resources/views/home/xuatban.blade.php
resources/views/partials/banner.blade.php
resources/views/story/index.blade.php

Hoangnv - Cập nhật Banner

---

app/Http/Controllers/SharedBookController.php
app/Models/chapter.php
resources/views/stories/iframe/sharebooks/list.blade.php
resources/views/story/layout/reading/slidebar.blade.php
resources/views/story/reading.blade.php

"Updated SharedBookController, Chapter model, and views for story reading and sharing functionality"

---

app/Http/Controllers/RatingController.php
app/Models/Like_books.php
app/Models/Like_rating.php
database/migrations/2024_10_25_224004_create_rating_likes_table.php

thay doi modal likes rating

---

app/Http/Controllers/Admin/adminGroupController.php
app/Http/Controllers/BookController.php
app/Http/Controllers/USER/HomeController.php
resources/views/home/group.blade.php
resources/views/story/layout/master.blade.php
resources/views/story/layout/reading/head.blade.php
resources/views/story/layout/reading/slidebar.blade.php
resources/views/story/show.blade.php
resources/views/user/cart/index.blade.php
routes/web.php

Sửa lại layout để dùng 1 layout duy nhất cho trang chủ. Thêm phần hiển thị group và truyện của group đó cho người dùng. 
sau sẽ làm lại phần thêm sửa xóa cho người dùng trong group

update lại layout cho reading và story. Thêm hiẻn thị group cho người dùng

---

app/Http/Controllers/Admin/StoryController.php
app/Http/Controllers/AutoPurchaseController.php
app/Http/Controllers/ChapterController.php
app/Models/AutoPurchase.php
app/Models/book.php
database/migrations/2024_11_19_083407_create_auto_purchases_table.php
resources/views/admin/stories/chapter/create.blade.php
resources/views/admin/stories/chapter/edit.blade.php
resources/views/stories/iframe/partials/scriptAjaxforChapter.blade.php
resources/views/story/show.blade.php
routes/web.php

done autopurchase

---

app/Http/Controllers/ChaptercommentController.php
app/Models/chaptercomment.php
database/migrations/2024_11_24_095246_add_id_delete_to_chapter_comments_table.php
public/scripts/app.js
resources/views/story/layout/reading/comment.blade.php
routes/web.php

Hoàn thành crud bằng ajax và jquery

đã xong hiển thị và xoá comment
